name: Tag Publisher

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "github.ref: ${{ github.ref }}"
          echo "github.actor: ${{ github.actor }}"
          
          if [ -n "${{ secrets.TRIGGER_GITHUB_TOKEN }}" ]; then
              echo "pat present"
          else
              echo "pat NOT present"
          fi

      - uses: actions/checkout@v3.1.0
        env:
          token: ${{ secrets.TRIGGER_GITHUB_TOKEN }}

      - name: Fetch all tags
        run: git fetch --tags --unshallow

      - name: Push tag
        run: |
          git config user.name "Creek-bot"
          git config user.email "95620007+Creek-Bot@users.noreply.github.com"
          echo
          echo "Adding tag ${{ github.event.inputs.tag }}"
          git tag -am "Tag: ${{ github.event.inputs.tag }}" ${{ github.event.inputs.tag }}
          echo
          echo "https://$GITHUB_ACTOR:${{ secrets.TRIGGER_GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git push --tags "https://$GITHUB_ACTOR:${{ secrets.TRIGGER_GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
